---
driver:
  name: docker
  hostname: rsyslog.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: rsyslog
  grains:
    noservices: True
  dependencies:
    - name: heka
      repo: git
      source: https://github.com/salt-formulas/salt-formula-heka
  state_top:
    base:
      "*":
        - rsyslog
  pillars:
    top.sls:
      base:
        "*":
          - rsyslog

verifier:
  name: inspec
  sudo: true


platforms:
  - name: <%=ENV['PLATFORM'] || 'ubuntu-xenial'%>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'trevorj/salty-whales:xenial'%>
      platform: ubuntu

suites:

  - name: client_single
    provisioner:
      pillars-from-files:
        rsyslog.sls: tests/pillar/client_single.sls

  - name: server_single
    provisioner:
      pillars-from-files:
        rsyslog.sls: tests/pillar/server_single.sls
# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
